"""Mortara (Welch Allyn / Hillrom) ELI XML parser.

Reads the native XML written by ELI electrocardiographs (ELI 250, ELI 280)
and ELI Link. No public specification exists; the layout follows real
exports and the open-source readers BRAVEHEART (``load_elixml.m``),
EDFbrowser (``mortara2edf.cpp``) and ecg2dcm:

- ``<ECG>`` root: ACQUISITION_TIME (yyyyMMddHHmmss), AGE/AGE_UNITS,
  HEIGHT/WEIGHT with *_UNITS, VENT_RATE, AVERAGE_RR, NUM_QRS, ...
- ``<SUBJECT>``: LAST_NAME, FIRST_NAME, ID, GENDER, DOB (yyyyMMdd), DOB_XML.
- ``<SOURCE>``: device, software versions, filters, TRANSMISSION_TIME.
- ``<AUTOMATIC_INTERPRETATION><STATEMENT TEXT REASON/>``: machine statements.
- ``<TYPICAL_CYCLE>``: global measurements, fiducials and median beats
  (``<TYPICAL_CYCLE_CHANNEL>``).
- ``<CHANNEL>``: rhythm leads, Base64 int16 LE, physical mV =
  raw / UNITS_PER_MV, DURATION = number of samples.
"""

from __future__ import annotations

import re
import warnings
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
from pathlib import Path

from ecgdatakit.exceptions import CorruptedFileError, UnsupportedFormatError
from ecgdatakit.models import (
    DeviceInfo,
    ECGRecord,
    FileFormatInfo,
    FilterSettings,
    GlobalMeasurements,
    Interpretation,
    Lead,
    PatientInfo,
    RecordingInfo,
    SignalCharacteristics,
    derive_is_raw,
)
from ecgdatakit.parsing.helpers import (
    fill_signal_summary,
    normalize_lead_label,
    unique_labels,
)
from ecgdatakit.parsing.helpers.waveform_text import decode_int16_text
from ecgdatakit.parsing.parser import Parser

_ROOT_RE = re.compile(r"<ECG[\s>/]")
_MARKERS = ("ACQUISITION_TIME", "<TYPICAL_CYCLE", "<CHANNEL", "<DEMOGRAPHIC_FIELDS",
            "<SUBJECT", "MORTARA", "WELCH ALLYN", "ELI LINK")
_GENERATOR_RE = re.compile(rb"<!--\s*Generated by\s+(.+?)\s*-->")

# DEMOGRAPHIC_FIELD@ID codes seen in exports (labels are localised)
_DEMOGRAPHIC_IDS = {"1": "last_name", "7": "first_name", "2": "id", "3": "age",
                    "4": "sex", "16": "dob"}

_HEIGHT_TO_CM = {"CM": 1.0, "M": 100.0, "IN": 2.54, "INCH": 2.54, "INCHES": 2.54}
_WEIGHT_TO_KG = {"KG": 1.0, "G": 0.001, "LB": 0.45359237, "LBS": 0.45359237}

_FIDUCIALS = ("R_PEAK", "P_ONSET", "P_OFFSET", "Q_ONSET", "Q_OFFSET", "T_OFFSET",
              "P_DURATION", "PR_DURATION", "QRS_DURATION", "QT", "QTC", "QTB",
              "QTF", "P_AXIS", "QRS_AXIS", "T_AXIS")

_CYCLE_FORMAT_KEYS = {"BITS", "FORMAT", "UNITS_PER_MV", "DURATION", "SAMPLE_FREQ",
                      "ENCODING"}


def _number(value: str | None) -> float | None:
    """Return *value* as a float, or ``None`` when empty or not numeric."""
    if value is None or not value.strip():
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _rounded(value: str | None) -> int | None:
    num = _number(value)
    return None if num is None else int(round(num))


def _parse_dob(value: str | None) -> datetime | None:
    """Parse yyyyMMdd or yyyy-MM-dd; all-zero placeholders give ``None``."""
    if not value or not value.strip():
        return None
    text = value.strip()
    if not text.strip("0-/"):
        return None
    for fmt in ("%Y%m%d", "%Y-%m-%d"):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            continue
    return None


def _years_between(start: datetime, end: datetime) -> int:
    return end.year - start.year - ((end.month, end.day) < (start.month, start.day))


def _sex(value: str | None) -> str:
    if not value or not value.strip():
        return ""
    first = value.strip()[0].upper()
    return first if first in ("M", "F") else "U"


class MortaraEL250Parser(Parser):
    """Parser for Mortara ELI XML ECG files (ELI 250 / ELI 280 / ELI Link)."""

    FORMAT_NAME = "Mortara EL250"
    FORMAT_DESCRIPTION = "Mortara ELI XML ECG format"
    FILE_EXTENSIONS = [".xml"]
    PRIORITY = 50

    @staticmethod
    def can_parse(file_path: Path, header: bytes) -> bool:
        text = header.decode("utf-8", errors="ignore")
        if not _ROOT_RE.search(text):
            return False
        upper = text.upper()
        return any(marker in upper for marker in _MARKERS)

    def parse(self, file_path: Path) -> ECGRecord:
        data = Path(file_path).read_bytes()
        try:
            root = ET.fromstring(data)
        except ET.ParseError as e:
            raise CorruptedFileError(f"Malformed Mortara XML in {file_path}: {e}") from e
        if root.tag != "ECG":
            raise CorruptedFileError(f"Missing ECG root element in {file_path}")

        record = ECGRecord(source_format="mortara_el250")
        raw = record.raw_metadata

        generator = _GENERATOR_RE.search(data[:2048])
        if generator:
            raw["generator"] = generator.group(1).decode("utf-8", errors="replace")

        source = root.find("SOURCE")
        src = dict(source.attrib) if source is not None else {}
        if src:
            raw["source"] = src

        leads, encodings, offsets = self._read_channels(root, file_path)
        if offsets:
            raw["channel_offsets"] = offsets
            warnings.warn(
                f"Mortara CHANNEL OFFSET is non-zero for {sorted(offsets)} and was "
                "not applied (undocumented); see raw_metadata['channel_offsets']",
                stacklevel=2,
            )
        if not leads:
            raise CorruptedFileError(f"No CHANNEL waveform data in {file_path}")
        record.leads = leads

        cycle = root.find("TYPICAL_CYCLE")
        record.median_beats = self._read_typical_cycle(cycle, leads, file_path, raw)

        record.recording = self._read_recording(root, leads)
        record.recording.device = self._read_device(src)
        record.recording.acquisition.filters = self._read_filters(src, raw)
        record.recording.acquisition.signal = SignalCharacteristics(
            sampling_rate=leads[0].sampling_rate,
            bits_per_sample=16,
            signal_signed=True,
            number_channels_valid=len(leads),
            number_channels_allocated=len(leads),
            data_encoding="base64_int16le" if encodings == {"base64_int16le"} else "",
            compression="none",
        )

        record.patient = self._read_patient(root, record.recording.date, raw)
        record.measurements, record.annotations = self._read_measurements(root, cycle, raw)
        record.interpretation = self._read_interpretation(root)

        transmission = src.get("TRANSMISSION_TIME_XML") or src.get("TRANSMISSION_TIME")
        created = self._parse_time(transmission)
        if created is not None:
            record.file_format = FileFormatInfo(creation_date=created.date())

        for key in ("SEQUENCE_NUMBER", "SYSTOLIC_BP", "DIASTOLIC_BP"):
            value = root.get(key, "").strip()
            if value:
                raw[key.lower()] = value
        site = root.find("SITE")
        if site is not None and site.attrib:
            raw["site"] = dict(site.attrib)

        fill_signal_summary(record)
        return record

    # -- waveforms ---------------------------------------------------------

    @staticmethod
    def _decode(node: ET.Element, where: str, file_path: Path) -> tuple:
        data = node.get("DATA")
        if data is None:
            data = node.text or ""
        try:
            samples, encoding = decode_int16_text(data)
        except ValueError as e:
            raise CorruptedFileError(f"{where} in {file_path}: {e}") from e
        if samples.size == 0:
            raise CorruptedFileError(f"{where} in {file_path} has no DATA")
        return samples, encoding

    @staticmethod
    def _check_format(attrs: dict, where: str) -> None:
        bits = attrs.get("BITS", "16").strip() or "16"
        fmt = attrs.get("FORMAT", "SIGNED").strip().upper() or "SIGNED"
        enc = attrs.get("ENCODING", "BASE64").strip().upper() or "BASE64"
        if bits != "16" or fmt != "SIGNED" or enc != "BASE64":
            raise UnsupportedFormatError(
                f"{where}: only 16-bit signed Base64 data is supported "
                f"(BITS={bits}, FORMAT={fmt}, ENCODING={enc})"
            )

    @staticmethod
    def _scale(upmv_str: str | None) -> tuple[float, str, float, str]:
        """Return (resolution, unit, adc_resolution, adc_unit) from UNITS_PER_MV."""
        upmv = _number(upmv_str)
        if upmv is None or upmv <= 0:
            return 1.0, "", 0.0, ""
        return 1000.0 / upmv, "uV", upmv, "counts/mV"

    @staticmethod
    def _rate(value: str | None, where: str, file_path: Path) -> int:
        rate = _number(value)
        if rate is None or rate <= 0:
            raise CorruptedFileError(f"{where} in {file_path}: invalid SAMPLE_FREQ {value!r}")
        return int(round(rate))

    def _make_lead(self, label, samples, rate, scale) -> Lead:
        resolution, unit, adc_res, adc_unit = scale
        is_raw = derive_is_raw(resolution, 0.0, unit)
        return Lead(
            label=label,
            samples=samples,
            sampling_rate=rate,
            resolution=resolution,
            resolution_unit=unit,
            units="" if is_raw else unit,
            is_raw=is_raw,
            adc_resolution=adc_res,
            adc_resolution_unit=adc_unit,
        )

    def _read_channels(self, root: ET.Element, file_path: Path) -> tuple[list[Lead], set, dict]:
        leads: list[Lead] = []
        encodings: set[str] = set()
        offsets: dict[str, str] = {}
        for i, ch in enumerate(root.findall("CHANNEL")):
            name = (ch.get("NAME") or "").strip()
            where = f"CHANNEL {name or i + 1}"
            self._check_format(ch.attrib, where)
            samples, encoding = self._decode(ch, where, file_path)
            encodings.add(encoding)
            rate = self._rate(ch.get("SAMPLE_FREQ"), where, file_path)

            # DURATION is the sample count (BRAVEHEART); accept milliseconds too
            duration = _number(ch.get("DURATION"))
            if duration is not None and duration > 0:
                n = samples.size
                if int(duration) != n and int(round(n * 1000 / rate)) != int(duration):
                    raise CorruptedFileError(
                        f"{where} in {file_path}: DURATION={ch.get('DURATION')} "
                        f"but DATA holds {n} samples"
                    )

            # OFFSET is 0 in every known export and its meaning is not
            # documented (BRAVEHEART adds it to the counts, EDFbrowser ignores it)
            offset = (ch.get("OFFSET") or "0").strip()
            if _number(offset) not in (None, 0.0):
                offsets[name] = offset

            leads.append(self._make_lead(
                normalize_lead_label(name) if name else f"CH{i + 1}",
                samples, rate, self._scale(ch.get("UNITS_PER_MV")),
            ))

        for lead, label in zip(leads, unique_labels([l.label for l in leads])):
            lead.label = label
        return leads, encodings, offsets

    def _read_typical_cycle(self, cycle, leads: list[Lead], file_path: Path, raw: dict) -> list[Lead]:
        if cycle is None:
            return []
        channels = cycle.findall("TYPICAL_CYCLE_CHANNEL")
        if not channels:
            return []
        self._check_format(cycle.attrib, "TYPICAL_CYCLE")
        if cycle.get("SAMPLE_FREQ"):
            rate = self._rate(cycle.get("SAMPLE_FREQ"), "TYPICAL_CYCLE", file_path)
        else:
            # Not stated for the median beats: the rhythm rate is used and reported
            rate = leads[0].sampling_rate
            raw["median_sampling_rate_stated"] = False
            warnings.warn(
                f"Mortara TYPICAL_CYCLE has no SAMPLE_FREQ, the rhythm rate ({rate} Hz) "
                "is used for the median beats",
                stacklevel=3,
            )
        upmv = cycle.get("UNITS_PER_MV")
        if _number(upmv) is None:
            # Not stated for the median beats: they stay in raw counts with no unit
            upmv = None
            raw["median_scale_stated"] = False
            warnings.warn(
                "Mortara TYPICAL_CYCLE has no UNITS_PER_MV, the median beats are left "
                "in raw counts",
                stacklevel=3,
            )
        scale = self._scale(upmv)

        beats: list[Lead] = []
        for i, ch in enumerate(channels):
            name = (ch.get("NAME") or "").strip()
            samples, _ = self._decode(ch, f"TYPICAL_CYCLE_CHANNEL {name or i + 1}", file_path)
            beats.append(self._make_lead(
                normalize_lead_label(name) if name else f"CH{i + 1}", samples, rate, scale,
            ))
        for beat, label in zip(beats, unique_labels([b.label for b in beats])):
            beat.label = label
        return beats

    # -- metadata ----------------------------------------------------------

    @staticmethod
    def _parse_time(value: str | None) -> datetime | None:
        if not value or not value.strip():
            return None
        text = value.strip()
        try:
            if "-" in text or "T" in text:
                return datetime.fromisoformat(text)
            return datetime.strptime(text, "%Y%m%d%H%M%S")
        except ValueError:
            return None

    def _read_recording(self, root: ET.Element, leads: list[Lead]) -> RecordingInfo:
        info = RecordingInfo()
        info.date = (self._parse_time(root.get("ACQUISITION_TIME_XML"))
                     or self._parse_time(root.get("ACQUISITION_TIME")))
        lead = leads[0]
        info.duration = timedelta(seconds=lead.samples.size / lead.sampling_rate)
        info.room = root.get("ROOM", "").strip()
        info.location = root.get("LOCATION", "").strip()
        info.technician = root.get("TECHNICIAN", "").strip()
        return info

    @staticmethod
    def _read_device(src: dict) -> DeviceInfo:
        return DeviceInfo(
            manufacturer=src.get("MANUFACTURER", "").strip(),
            model=(src.get("MODEL", "").strip()
                   or src.get("ACQUIRING_DEVICE_EXTENDED_MODEL_DESCRIPTION", "").strip()),
            serial_number=src.get("ACQUIRING_DEVICE_SERIAL_NUMBER", "").strip(),
            software_version=src.get("ACQUIRING_DEVICE_SW_VERSION", "").strip(),
            institution=src.get("ACQUIRING_DEVICE_SITE_NAME", "").strip(),
            acquisition_type=src.get("TYPE", "").strip(),
        )

    @staticmethod
    def _read_filters(src: dict, raw: dict) -> FilterSettings:
        filters = FilterSettings()
        lowpass = _number(src.get("LOW_PASS_FILTER"))
        if lowpass:
            filters.lowpass = lowpass
        # Coding of these settings is undocumented: kept as written
        other = {k: src[k] for k in ("BASELINE_ROLL_FILTER", "PRINT_FILTER", "FILTER_BITMAP")
                 if src.get(k, "").strip()}
        if other:
            raw["filters"] = other
        return filters

    def _read_patient(self, root: ET.Element, acq_date: datetime | None, raw: dict) -> PatientInfo:
        info = PatientInfo()
        subject = root.find("SUBJECT")
        subj = dict(subject.attrib) if subject is not None else {}

        demo: dict[str, str] = {}
        fields = root.findall("DEMOGRAPHIC_FIELDS/DEMOGRAPHIC_FIELD")
        if fields:
            raw["demographic_fields"] = [dict(f.attrib) for f in fields]
        for f in fields:
            key = _DEMOGRAPHIC_IDS.get((f.get("ID") or "").strip())
            value = (f.get("VALUE") or "").strip()
            if key and value:
                demo[key] = value
                if key == "age":
                    demo["age_units"] = (f.get("UNITS") or "").strip()

        info.last_name = subj.get("LAST_NAME", "").strip() or demo.get("last_name", "")
        info.first_name = subj.get("FIRST_NAME", "").strip() or demo.get("first_name", "")
        info.patient_id = (subj.get("ID", "").strip() or subj.get("LOCAL_ID", "").strip()
                           or demo.get("id", ""))
        info.sex = _sex(subj.get("GENDER")) or _sex(demo.get("sex"))
        info.birth_date = (_parse_dob(subj.get("DOB_XML")) or _parse_dob(subj.get("DOB"))
                           or _parse_dob(demo.get("dob")))
        race = subj.get("RACE", "").strip()
        if race:
            info.race = race

        age = root.get("AGE", "").strip() or demo.get("age", "")
        units = (root.get("AGE_UNITS", "").strip() if root.get("AGE", "").strip()
                 else demo.get("age_units", "")).upper()
        value = _number(age)
        if value is not None:
            if units in ("", "Y", "YEARS"):
                info.age = int(value)
            else:
                raw["age"] = {"value": age, "units": units}
        if info.age is None and info.birth_date is not None and acq_date is not None:
            info.age = _years_between(info.birth_date, acq_date)

        height = _number(root.get("HEIGHT"))
        if height:
            unit = root.get("HEIGHT_UNITS", "").strip().upper()
            if unit in _HEIGHT_TO_CM:
                info.height = round(height * _HEIGHT_TO_CM[unit], 2)
            else:
                raw["height"] = {"value": root.get("HEIGHT"), "units": unit}
        weight = _number(root.get("WEIGHT"))
        if weight:
            unit = root.get("WEIGHT_UNITS", "").strip().upper()
            if unit in _WEIGHT_TO_KG:
                info.weight = round(weight * _WEIGHT_TO_KG[unit], 3)
            else:
                raw["weight"] = {"value": root.get("WEIGHT"), "units": unit}

        meds = root.findall("MEDICATION")
        info.medications = [m.get("NAME").strip() for m in meds if (m.get("NAME") or "").strip()]
        coded = [dict(m.attrib) for m in meds
                 if (m.get("NAME") or "").strip()
                 or (m.get("CLASS_CODE") or "0").strip() not in ("", "0")
                 or (m.get("DRUG_CODE") or "0").strip() not in ("", "0")]
        if coded:
            raw["medications"] = coded
        return info

    @staticmethod
    def _read_measurements(root: ET.Element, cycle, raw: dict):
        m = GlobalMeasurements()
        annotations: dict[str, str] = {}
        tc = dict(cycle.attrib) if cycle is not None else {}

        m.heart_rate = _rounded(root.get("VENT_RATE"))
        m.rr_interval = _rounded(root.get("AVERAGE_RR"))
        m.qrs_count = _rounded(root.get("NUM_QRS"))
        m.pr_interval = _rounded(tc.get("PR_DURATION"))
        m.qrs_duration = _rounded(tc.get("QRS_DURATION"))
        m.qt_interval = _rounded(tc.get("QT"))
        m.qtc_bazett = _rounded(tc.get("QTB"))
        m.qtc_fridericia = _rounded(tc.get("QTF"))
        m.p_axis = _rounded(tc.get("P_AXIS"))
        m.qrs_axis = _rounded(tc.get("QRS_AXIS"))
        m.t_axis = _rounded(tc.get("T_AXIS"))

        # QTC uses an undocumented correction (neither Bazett nor Fridericia)
        qtc = _rounded(tc.get("QTC"))
        if qtc is not None:
            raw["qtc"] = qtc

        for key in ("VENT_RATE", "AVERAGE_RR", "NUM_QRS"):
            value = root.get(key, "").strip()
            if value:
                annotations[key.lower()] = value
        # Fiducials in ms relative to the median beat, as written
        for key, value in tc.items():
            if key not in _CYCLE_FORMAT_KEYS and value.strip():
                annotations[key.lower()] = value.strip()
        comment = root.get("COMMENT", "").strip()
        if comment:
            annotations["comment"] = comment
        return m, annotations

    @staticmethod
    def _read_interpretation(root: ET.Element) -> Interpretation:
        interp = Interpretation()
        statements: list[tuple[str, str]] = []
        for node in root.findall("AUTOMATIC_INTERPRETATION/STATEMENT"):
            text = (node.get("TEXT") or node.text or "").strip()
            reason = (node.get("REASON") or "").strip()
            if text:
                statements.append((text, reason))
        if statements:
            interp.statements = statements
            interp.source = "machine"
            severity = (root.get("SEVERITY") or "").strip()
            if severity:
                interp.severity = severity.upper()
        return interp
